export const EnvironmentModel = {
  vars: {
    // GLOBAL CONFIGURATION
    NODE_ENV: 'DEV',

    // AUTH MICROSERVICE CONFIGURATION
    SIMPLE_KAMBAM_TASK_DB_PASSWORD: 'simple_kambam',
    SIMPLE_KAMBAM_TASK_DB_USERNAME: 'simple_kambam',
    SIMPLE_KAMBAM_TASK_DB_NAME: 'simple_kambam',
    SIMPLE_KAMBAM_TASK_DB_PORT: 65_006,
    SIMPLE_KAMBAM_TASK_DATABASE_URL:
      'postgresql://simple_kambam:simple_kambam@localhost:65006/simple_kambam?schema=public',
    SIMPLE_KAMBAM_AUTH_PORT: 30_000,
    SIMPLE_KAMBAM_AUTH_CLIENT: 'authentication-client',
    SIMPLE_KAMBAM_AUTH_CONSUMER: 'authentication-consumer',
    SIMPLE_KAMBAM_AUTH_PRODUCER: 'authentication-producer',

    // KAFKA CONFIGURATION
    KAFKA_BROKER_URL: 'pkc-2396y.us-east-1.aws.confluent.cloud:9092',
    USE_KAFKA: false,
    KAFKA_MECHANISM: 'plain',
    KAFKA_USERNAME: '3CKHTGEVAYUBDGQY',
    KAFKA_PASSWORD:
      'J2Q0N+m+WTRhz4Ou3BNYicg035IXW31QeUlsNuKiTvKukuSOYRBr3GhUqmQc6IfO',
    KAFKA_AUTH_TIMEOUT: 45_000,
  },

  setVars({
    SIMPLE_KAMBAM_TASK_DB_PASSWORD,
    SIMPLE_KAMBAM_TASK_DB_USERNAME,
    SIMPLE_KAMBAM_TASK_DB_NAME,
    SIMPLE_KAMBAM_TASK_DB_PORT,
    SIMPLE_KAMBAM_TASK_DATABASE_URL,
    SIMPLE_KAMBAM_AUTH_PORT,
    SIMPLE_KAMBAM_AUTH_PRODUCER,
    SIMPLE_KAMBAM_AUTH_CONSUMER,
    NODE_ENV,
    KAFKA_USERNAME,
    KAFKA_PASSWORD,

    KAFKA_MECHANISM,
    USE_KAFKA,
    KAFKA_BROKER_URL,
    KAFKA_AUTH_TIMEOUT,
    SIMPLE_KAMBAM_AUTH_CLIENT,
  }: unknown): void {
    this.vars = {
      SIMPLE_KAMBAM_AUTH_CLIENT,
      KAFKA_AUTH_TIMEOUT,
      KAFKA_MECHANISM,
      KAFKA_USERNAME,
      KAFKA_PASSWORD,
      USE_KAFKA,
      NODE_ENV,
      KAFKA_BROKER_URL,
      SIMPLE_KAMBAM_TASK_DB_PASSWORD,
      SIMPLE_KAMBAM_TASK_DB_USERNAME,
      SIMPLE_KAMBAM_TASK_DB_NAME,
      SIMPLE_KAMBAM_TASK_DB_PORT,
      SIMPLE_KAMBAM_TASK_DATABASE_URL,
      SIMPLE_KAMBAM_AUTH_PORT,
      SIMPLE_KAMBAM_AUTH_CONSUMER,
      SIMPLE_KAMBAM_AUTH_PRODUCER,
    };
  },
};
