export enum BussinessErrorsNames {
  EMIT_TOKEN_ERROR = 'EMIT_TOKEN_ERROR',
  ENCRYPTION_ERROR = 'ENCRYPTION_ERROR',
  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  CANNOT_CREATE_USER_ERROR = 'CANNOT_CREATE_USER_ERROR',
  SAVE_TOKEN_ERROR = 'SAVE_TOKEN_ERROR',
  SEND_TOKEN_ERROR = 'SEND_TOKEN_ERROR',
  USER_NOT_USE_EMAIL_AND_PASSWORD_AUTHENTICATION = 'USER_NOT_USE_EMAIL_AND_PASSWORD_AUTHENTICATION',
  SCHEDULE_REMOVE_2FA_TOKEN_ERROR = 'SCHEDULE_REMOVE_2FA_TOKEN_ERROR',
}
