version: '3.8'
services:
  postgres:
    container_name: simple_kambam_auth_database
    image: postgres:14-alpine3.15
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${SIMPLE_KAMBAM_TASK_DB_PASSWORD}
      POSTGRES_USER: ${SIMPLE_KAMBAM_TASK_DB_USERNAME}
      POSTGRES_DB: ${SIMPLE_KAMBAM_TASK_DB_NAME}
    ports:
      - '${SIMPLE_KAMBAM_TASK_DB_PORT}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata:
